"""Generate an exact, readable model/source reference using only Python's stdlib."""

import hashlib
import json
import re
from pathlib import Path
from zipfile import ZipFile


ROOT = Path(__file__).resolve().parents[1]


def code(value, language="json"):
    body = value if isinstance(value, str) else json.dumps(value, indent=2, ensure_ascii=False)
    return f"```{language}\n{body}\n```\n"


def describe_layer(layer, prefix=""):
    config = dict(layer["config"])
    children = config.pop("layers", [])
    name = prefix + config.get("name", layer["class_name"])
    yield f"### `{name}` — {layer['class_name']}\n"
    details = {"config": config}
    for key in ("build_config", "inbound_nodes"):
        if key in layer:
            details[key] = layer[key]
    yield code(details)
    for child in children:
        yield from describe_layer(child, name + "/")


def main():
    model = ROOT / "ml/models/best_model.keras"
    with ZipFile(model) as archive:
        config = json.loads(archive.read("config.json"))
        metadata = json.loads(archive.read("metadata.json"))
        entries = [{"file": x.filename, "bytes": x.file_size} for x in archive.infolist()]
    parts = [
        "# Exact Implementation Reference\n",
        "Generated by `python3 ml/inspect_artifact.py`. This is an artifact and source inventory, "
        "not evidence of dataset provenance or achieved training metrics. Read "
        "[the technical guide](TECHNICAL_GUIDE.md) for explanations.\n",
        "## Artifact identity\n",
        code({"path": "ml/models/best_model.keras", "bytes": model.stat().st_size,
              "sha256": hashlib.sha256(model.read_bytes()).hexdigest(),
              "metadata": metadata, "archive_entries": entries}),
        "## Saved compile configuration\n",
        code(config.get("compile_config")),
        "## Layer inventory\n",
        "The table includes the outer model layers and every nested backbone layer. "
        "Trainable flags include layers with no parameters. Input shapes and saved graph calls "
        "are reproduced in the detailed records below.\n",
        "| Path | Class | Trainable |\n| --- | --- | --- |",
    ]

    def rows(layers, prefix=""):
        for layer in layers:
            cfg = layer["config"]
            name = prefix + cfg.get("name", layer["class_name"])
            yield f"| `{name}` | {layer['class_name']} | {cfg.get('trainable', 'not set')} |"
            yield from rows(cfg.get("layers", []), name + "/")

    parts.extend(rows(config["config"]["layers"]))
    parts += ["\n## API method inventory\n", "| Endpoint | Methods | Source |\n| --- | --- | --- |"]
    for route in sorted((ROOT / "frontend/src/app/api").rglob("route.ts")):
        methods = re.findall(r"export async function (GET|POST|PATCH|PUT|DELETE|OPTIONS|HEAD)\b", route.read_text())
        endpoint = "/api/" + str(route.parent.relative_to(ROOT / "frontend/src/app/api"))
        relative = route.relative_to(ROOT)
        parts.append(f"| `{endpoint}` | {', '.join(methods)} | [route](../{relative.as_posix()}) |")
    parts += ["\n## Database schema: every field, relation, index and enum\n",
              code((ROOT / "frontend/prisma/schema.prisma").read_text(), "prisma"),
              "## Declared JavaScript dependencies and scripts\n",
              code(json.loads((ROOT / "frontend/package.json").read_text())),
              "## Python requirement pins\n",
              code((ROOT / "ml/requirements.txt").read_text(), "text"),
              "## Detailed layer records\n",
              "These records reproduce the artifact's settings, including initializers, regularizers, "
              "constraints, dtype policies, shapes, connections, and saved call arguments. "
              "Serialization IDs are not random seeds or training-run identifiers.\n"]
    for layer in config["config"]["layers"]:
        parts.extend(describe_layer(layer))
    output = ROOT / "docs/IMPLEMENTATION_REFERENCE.md"
    output.write_text("\n".join(parts), encoding="utf-8")
    print(f"Wrote {output.relative_to(ROOT)} ({output.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
